apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-globo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-globo
  template:
    metadata:
      labels:
        app: app-globo
    spec:
      containers:
      - name: app-globo-container
        image: fernandohs99/app_globo:29
        ports:
        - containerPort: 5000
