apiVersion: v1
kind: Pod
metadata:
  name: app-globo-pod
  labels:
    app: app-globo
spec:
  containers:
    - name: app-globo-container
      image: fernandohs99/app_globo:${BUILD_ID}
      ports:
        - containerPort: 5000
